Web/Models/ErrorViewModel.cs
using System;

namespace Web.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Web/Controllers/CategoryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Xml;
using System.Xml.Linq;
using BusinessLogic;
using BusinessObject;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;

namespace Web.Controllers
{
    public class CategoryController : Controller
    {
        private IHostingEnvironment _hostingEnvironment;
        CategoryBL categoryBL;

        /// <summary>
        /// Category Controller
        /// </summary>
        /// <param name="environment"></param>
        public CategoryController(IHostingEnvironment environment)
        {
            _hostingEnvironment = environment;
            categoryBL = new CategoryBL(_hostingEnvironment);
        }

        /// <summary>
        /// Get Category Details
        /// </summary>
        /// <returns></returns>
        public IActionResult CategoryDetails()
        {
            IEnumerable<CategoryObject> listCategoryObject;
            listCategoryObject=categoryBL.GetAllCategory();
            return View(listCategoryObject);
        }

        /// <summary>
        /// Return Create Category Page
        /// </summary>
        /// <returns></returns>
        public IActionResult Create()
        {
            return View();
        }

        /// <summary>
        /// Edit Category
        /// </summary>
        /// <param name="CategoryId"></param>
        /// <returns></returns>
        public IActionResult EditCategory(int CategoryId)
        {
            CategoryObject categoryObject = new CategoryObject();
            categoryObject = categoryBL.CategoryEdit(CategoryId);
            if (categoryObject != null)
            {
                return View(categoryObject);
            }
            else
            {
                return RedirectToAction("CategoryDetails");
            }
        }

        /// <summary>
        /// Delete Category
        /// </summary>
        /// <param name="CategoryId"></param>
        /// <returns></returns>
        public IActionResult DeleteCategory(int CategoryId)
        {
            categoryBL.DeleteCategory(CategoryId);
            return RedirectToAction("CategoryDetails");
        }

        /// <summary>
        /// Create Category Post
        /// </summary>
        /// <param name="categoryObject"></param>
        /// <returns></returns>
        public IActionResult CreateCategory([Bind] CategoryObject categoryObject)
        {
            int result = 0;
            if (ModelState.IsValid)
            {
                result =categoryBL.SaveUpdateCategory(categoryObject);
                if(result>0)
                {
                    return RedirectToAction("CategoryDetails");
                }
                else
                {
                    ModelState.AddModelError("CategoryName", "Already Exist");
                    return RedirectToAction("Create");
                }
            }
            else
            {
                ViewBag.Issue = false;
                return View("Create");
            }
        }
    }
}

Web/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Web.Models;

namespace Web.Controllers
{
    public class HomeController : Controller
    {
       
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult About()
        {
            ViewData["Message"] = "Your application description page.";

            return View();
        }

        public IActionResult Contact()
        {
            ViewData["Message"] = "Your contact page.";

            return View();
        }
      


        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Web/Controllers/LoginController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using BusinessLogic;
using BusinessObject;
using Microsoft.AspNetCore.Mvc;

namespace Web.Controllers
{
    public class LoginController : Controller
    {
        UserBL userBL = new UserBL();

        /// <summary>
        /// Login View Return
        /// </summary>
        /// <returns></returns>
        public IActionResult Login()
        {
            return View();
        }

        /// <summary>
        /// User Login Post
        /// </summary>
        /// <param name="cust"></param>
        /// <returns></returns>
        [HttpPost]
        public IActionResult UserLogin([Bind] LoginObject cust)
        {
            if (ModelState.IsValid)
            {
                if (userBL.LoginUser(cust))
                {
                    return Redirect("/Category/CategoryDetails");
                }
                else
                {
                    ViewData["InvalidLogin"] = "Invalid User Name or Password";
                    return View("Login");
                }
            }
            else
            {
                return View("Login");
            }
        }
    }
}

Web/Controllers/ProjectController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using BusinessLogic;
using BusinessObject;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;

namespace Web.Controllers
{
    public class ProjectController : Controller
    {
        private IHostingEnvironment _hostingEnvironment;
        ProjectBL projectBL;
        CategoryBL categoryBL;

        /// <summary>
        /// Project Controller Constructor
        /// </summary>
        /// <param name="environment"></param>
        public ProjectController(IHostingEnvironment environment)
        {
            _hostingEnvironment = environment;
            projectBL = new ProjectBL(_hostingEnvironment);
            categoryBL = new CategoryBL(_hostingEnvironment);
        }

        /// <summary>
        /// Get All Project Details
        /// </summary>
        /// <returns></returns>
        public IActionResult ProjectDetails()
        {
            IEnumerable<ProjectObject> listProjectObject;
            listProjectObject = projectBL.GetAllProjects();
            return View(listProjectObject);
        }

        /// <summary>
        /// Create New Project View
        /// </summary>
        /// <returns></returns>
        public IActionResult Create()
        {
            ViewBag.listCategoryObject = categoryBL.GetAllCategory();
            return View();
        }

        /// <summary>
        /// Create Project Api
        /// </summary>
        /// <param name="projectObject"></param>
        /// <returns></returns>
        public IActionResult CreateProject([Bind] ProjectObject projectObject)
        {
            int result = 0;
            if (ModelState.IsValid)
            {
                result = projectBL.SaveUpdateProject(projectObject);
                if (result > 0)
                {
                    return RedirectToAction("ProjectDetails");
                }
                else
                {
                    ViewBag.listCategoryObject = categoryBL.GetAllCategory(); 
                    return RedirectToAction("Create");
                }
            }
            else
            {
                ViewBag.listCategoryObject = categoryBL.GetAllCategory();
                return View("Create");
            }
        }

        /// <summary>
        /// Edit Api
        /// </summary>
        /// <param name="projectId"></param>
        /// <returns></returns>
        public IActionResult EditProject(int projectId)
        {
            ProjectObject projectObject = new ProjectObject();
            projectObject = projectBL.ProjectEdit(projectId);
            if (projectObject != null)
            {
                ViewBag.listCategoryObject = categoryBL.GetAllCategory();
                return View(projectObject);
            }
            else
            {
                return RedirectToAction("ProjectDetails");
            }
        }

        /// <summary>
        /// Delete Project
        /// </summary>
        /// <param name="projectId"></param>
        /// <returns></returns>
        public IActionResult DeleteProject(int projectId)
        {
            projectBL.DeleteProject(projectId);
            return RedirectToAction("ProjectDetails");
        }
    }
}

Web/Views/Category/CategoryDetails.cshtml
@model IEnumerable<BusinessObject.CategoryObject>;

@{
    ViewData["Title"] = "CategoryDetails";
}
<section class="content">
    <div class="row">
        <div class="col-md-12" style="opacity: 1.0;">
            <div class="box box-primary" style="margin-bottom: 5px!important;border-top:0px;">
                <div class="col-md-12" style="opacity: 1.0;">
                    <div class="col-md-6">
                        <h3>Category Details</h3>
                    </div>
                    <div class="col-md-6">
                        <a asp-controller="Category" asp-action="Create" style="margin-top: 12px;float:right;" class="btn btn-primary">Add Category</a>
                    </div>
                    <hr />
                </div>
            </div>
        </div>
    </div>
    <div class="box">
        <div class="box-body">
            <table class="order-report">
                <thead>
                    <tr>
                        <th>Category Name</th>
                        <th>Actions</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.CategoryName)
                            </td>
                            <td>
                                <a asp-action="EditCategory" asp-route-CategoryId="@item.CategoryId">Edit</a> |
                                <a asp-action="DeleteCategory" asp-route-CategoryId="@item.CategoryId">Delete</a>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>

</section>
<style>

    .order-report {
        width: 100% !important;
    }

        .order-report table {
            border-collapse: collapse;
            border-spacing: 0;
            width: 100%;
            margin-top: 15px;
        }

        .order-report th {
            padding-top: 11px;
            padding-bottom: 11px;
            background-color: #4CAF50;
            color: white;
        }

        .order-report td, .order-report th {
            border: 1px solid #ddd;
            text-align: left;
            padding: 8px;
        }

        .order-report tr:nth-child(even) {
            background-color: #f2f2f2;
        }

</style>

Web/Views/Category/Create.cshtml
@model BusinessObject.CategoryObject;
@{
    ViewData["Title"] = "Create Category";
}

<section class="content">
    <div class="row">
        <div class="col-md-12" style="opacity: 1.0;">
            <div class="box box-primary" style="margin-bottom: 5px!important;border-top: 0px;">
                <div class="col-md-12" style="opacity: 1.0;border-bottom: solid gray 1px;" >
                    <div class="col-md-6">
                        <h3>Create Category</h3>
                    </div>
                    <div class="col-md-6">
                        <a asp-controller="Category" asp-action="CategoryDetails" style="margin-top: 12px;float:right;" class="btn btn-primary">Back to Category</a>
                    </div>
                    <hr />
                </div>
                <form asp-action="CreateCategory">
                    <div class="box-body">
                        <div class="form-group col-sm-6">
                            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                            <label asp-for="CategoryName" class="control-label"></label>
                            <input asp-for="CategoryName" class="form-control" placeholder="Category" />
                            <span asp-validation-for="CategoryName" class="text-danger"></span>
                        </div>


                    </div>
                    <div class="pull-left">
                        <button type="submit" class="btn btn-primary">Save</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
   

</section>

Web/Views/Category/EditCategory.cshtml
@model BusinessObject.CategoryObject;
@{
    ViewData["Title"] = "EditCategory";
}

<section class="content">
    <div class="row">
        <div class="col-md-12" style="opacity: 1.0;">
            <div class="box box-primary" style="margin-bottom: 5px!important;border-top: 0px;">
                <div class="col-md-12" style="opacity: 1.0;">
                    <div class="col-md-6">
                        <h3>Edit Category</h3>
                    </div>
                    <div>
                        <a asp-controller="Category" asp-action="CategoryDetails" style="margin-top: 12px;float:right;" class="btn btn-primary">Back to List</a>
                    </div>
                    <div class="clearfix"></div>
                    <hr />
                </div>
                <form asp-action="CreateCategory">
                    <div class="box-body">
                        <div class="form-group col-sm-6">
                            <input type="hidden" asp-for="CategoryId" />
                            <label asp-for="CategoryName" class="control-label"></label>
                            <input asp-for="CategoryName" class="form-control" placeholder="Category" />
                            <span asp-validation-for="CategoryName" class="text-danger"></span>
                        </div>
                    </div>
                    <div class="pull-left">
                        <button type="submit" class="btn btn-primary">Save</button>
                       
                    </div>
                </form>
            </div>
        </div>
    </div>


</section>

Web/Views/Project/Create.cshtml
@model BusinessObject.ProjectObject;
@{
    ViewData["Title"] = "CreateProject";
}
<section class="content">
    <div class="row">
        <div class="col-md-12" style="opacity: 1.0;">
            <div class="box box-primary" style="margin-bottom: 5px!important;border-top: 0px;">
                <div class="col-md-12" style="opacity: 1.0;border-bottom: solid gray 1px;">
                    <div class="col-md-6">
                        <h3>Create Project</h3>
                    </div>
                    <div class="col-md-6">
                        <a asp-controller="Project" asp-action="ProjectDetails" style="margin-top: 12px;float:right;" class="btn btn-primary">Back to Project</a>
                    </div>
                    <hr />
                </div>



                <form asp-controller="Project" asp-action="CreateProject"  method="POST">
                        <div class="box-body">
                            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                            <div class="form-group col-sm-4">
                                <label asp-for="CategoryName" class="control-label"></label>
                                <select asp-for="CategoryName"
                                        class="form-control"
                                        asp-items="@(new SelectList(@ViewBag.listCategoryObject,"CategoryName", "CategoryName"))"></select>
                                <span asp-validation-for="CategoryName" class="text-danger"></span>
                            </div>
                            <div class="form-group col-sm-4">
                                <label asp-for="Description" class="control-label"></label>
                                <input asp-for="Description" class="form-control" placeholder="Description" />
                                <span asp-validation-for="Description" class="text-danger"></span>
                            </div>
                            <div class="form-group col-sm-4">
                                <label asp-for="Impact" class="control-label"></label>
                                <input asp-for="Impact" class="form-control" placeholder="Impact" />
                                <span asp-validation-for="Impact" class="text-danger"></span>
                            </div>
                            <div class="form-group col-sm-4">
                                <label asp-for="Causes" class="control-label"></label>
                                <input asp-for="Causes" class="form-control" placeholder="Causes" />
                                <span asp-validation-for="Causes" class="text-danger"></span>
                            </div>
                            <div class="form-group col-sm-4">
                                <label asp-for="CentreforPuralAction" class="control-label"></label>
                                <input asp-for="CentreforPuralAction" class="form-control" placeholder="Centre for Pural Action" />
                                <span asp-validation-for="CentreforPuralAction" class="text-danger"></span>
                            </div>
                            <div class="form-group col-sm-4">
                                <label asp-for="Requirements" class="control-label"></label>
                                <input asp-for="Requirements" class="form-control" placeholder="Requirements" />
                                <span asp-validation-for="Requirements" class="text-danger"></span>
                            </div>
                            <div class="form-group col-sm-4">
                                <label asp-for="SkillsNeeded" class="control-label"></label>
                                <input asp-for="SkillsNeeded" class="form-control" placeholder="Skills Needed" />
                                <span asp-validation-for="SkillsNeeded" class="text-danger"></span>
                            </div>
                            <div class="form-group col-sm-4">
                                <label asp-for="Duration" class="control-label"></label>
                                <input asp-for="Duration" class="form-control" placeholder="Duration" />
                                <span asp-validation-for="Duration" class="text-danger"></span>
                            </div>
                            <div class="form-group col-sm-4">
                                <label asp-for="TimeCommitment" class="control-label"></label>
                                <input asp-for="TimeCommitment" class="form-control" placeholder="TimeCommitment" />
                                <span asp-validation-for="TimeCommitment" class="text-danger"></span>
                            </div>
                            <div class="form-group col-sm-4">
                                <label asp-for="TimePeriod" class="control-label"></label>
                                <input asp-for="TimePeriod" class="form-control" placeholder="TimePeriod" />
                                <span asp-validation-for="TimePeriod" class="text-danger"></span>
                            </div>

                        </div>
                        <div class="pull-left">
                            <button type="submit" class="btn btn-primary">Save</button>
                        </div>
                    </form>
            </div>
        </div>
    </div>


</section>

Web/Views/Project/EditProject.cshtml
@model BusinessObject.ProjectObject;
@{
    ViewData["Title"] = "CreateProject";
}
<section class="content">
    <div class="row">
        <div class="col-md-12" style="opacity: 1.0;">
            <div class="box box-primary" style="margin-bottom: 5px!important;border-top: 0px;">
                <div class="col-md-12" style="opacity: 1.0;border-bottom: solid gray 1px;">
                    <div class="col-md-6">
                        <h3>Create Project</h3>
                    </div>
                    <div class="col-md-6">
                        <a asp-controller="Project" asp-action="ProjectDetails" style="margin-top: 12px;float:right;" class="btn btn-primary">Back to Project</a>
                    </div>
                    <hr />
                </div>



                <form asp-controller="Project" asp-action="CreateProject" method="POST">
                    <div class="box-body">
                        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                        <div class="form-group col-sm-4">
                            <input type="hidden" asp-for="ProjectId" />
                            <label asp-for="CategoryName" class="control-label"></label>
                            <select asp-for="CategoryName"
                                    class="form-control"
                                    asp-items="@(new SelectList(@ViewBag.listCategoryObject,"CategoryName", "CategoryName"))"></select>
                            <span asp-validation-for="CategoryName" class="text-danger"></span>
                        </div>
                        <div class="form-group col-sm-4">
                            <label asp-for="Description" class="control-label"></label>
                            <input asp-for="Description" class="form-control" placeholder="Description" />
                            <span asp-validation-for="Description" class="text-danger"></span>
                        </div>
                        <div class="form-group col-sm-4">
                            <label asp-for="Impact" class="control-label"></label>
                            <input asp-for="Impact" class="form-control" placeholder="Impact" />
                            <span asp-validation-for="Impact" class="text-danger"></span>
                        </div>
                        <div class="form-group col-sm-4">
                            <label asp-for="Causes" class="control-label"></label>
                            <input asp-for="Causes" class="form-control" placeholder="Causes" />
                            <span asp-validation-for="Causes" class="text-danger"></span>
                        </div>
                        <div class="form-group col-sm-4">
                            <label asp-for="CentreforPuralAction" class="control-label"></label>
                            <input asp-for="CentreforPuralAction" class="form-control" placeholder="Centre for Pural Action" />
                            <span asp-validation-for="CentreforPuralAction" class="text-danger"></span>
                        </div>
                        <div class="form-group col-sm-4">
                            <label asp-for="Requirements" class="control-label"></label>
                            <input asp-for="Requirements" class="form-control" placeholder="Requirements" />
                            <span asp-validation-for="Requirements" class="text-danger"></span>
                        </div>
                        <div class="form-group col-sm-4">
                            <label asp-for="SkillsNeeded" class="control-label"></label>
                            <input asp-for="SkillsNeeded" class="form-control" placeholder="Skills Needed" />
                            <span asp-validation-for="SkillsNeeded" class="text-danger"></span>
                        </div>
                        <div class="form-group col-sm-4">
                            <label asp-for="Duration" class="control-label"></label>
                            <input asp-for="Duration" class="form-control" placeholder="Duration" />
                            <span asp-validation-for="Duration" class="text-danger"></span>
                        </div>
                        <div class="form-group col-sm-4">
                            <label asp-for="TimeCommitment" class="control-label"></label>
                            <input asp-for="TimeCommitment" class="form-control" placeholder="TimeCommitment" />
                            <span asp-validation-for="TimeCommitment" class="text-danger"></span>
                        </div>
                        <div class="form-group col-sm-4">
                            <label asp-for="TimePeriod" class="control-label"></label>
                            <input asp-for="TimePeriod" class="form-control" placeholder="TimePeriod" />
                            <span asp-validation-for="TimePeriod" class="text-danger"></span>
                        </div>

                    </div>
                    <div class="pull-left">
                        <button type="submit" class="btn btn-primary">Save</button>
                    </div>
                </form>
            </div>
        </div>
    </div>


</section>

Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Web</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
        <link rel="stylesheet" href="~/dist/css/AdminLTE.min.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">Web</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Category" asp-action="CategoryDetails">Category</a></li>
                    <li><a asp-area="" asp-controller="Project" asp-action="ProjectDetails">Project</a></li>
                </ul>
            </div>
        </div>
    </nav>

    <partial name="_CookieConsentPartial" />

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2019 - Web</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-aJ21OjlMXNL5UyIl/XNwTMqvzeRMZH2w8c5cRVpzpU8Y5bApTppSuUkhZXN0VxHd">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>